name: Add Emoji
on: [push]

jobs:
  add-emoji:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Add emoji ğŸ¥°
        uses: tiena2cva/action-emoji@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
